# Generated by Django 5.0.3 on 2024-03-16 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='ProductModel',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='name',
            new_name='brandname',
        ),
    ]
