# Generated by Django 5.0.3 on 2024-03-17 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_model_productmodel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductModel',
            new_name='Model',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='brandname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.AddField(
            model_name='brand',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='blog.product'),
        ),
    ]
